version: '3.9'
name: restaurant-file-store-svc

services:
  mongodb:
    image: mongo:latest
    networks:
      - project-network
    container_name: restaurant-file-store-db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb-db:/data/db
      - mongodb-configdb:/data/configdb
volumes:
  mongodb-db:
    name: restaurant-file-store-db-pv-datadb
    external: false
  mongodb-configdb:
    name: restaurant-file-store-db-pv-dataconfigdb
    external: false
networks:
  project-network:
    name: restaurant
    external: true