receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  
exporters:
  debug:
    verbosity: detailed


extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
