// Code generated by mockery v2.38.0. DO NOT EDIT.

package file

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockFileMetadataRepository is an autogenerated mock type for the FileMetadataRepository type
type MockFileMetadataRepository struct {
	mock.Mock
}

type MockFileMetadataRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileMetadataRepository) EXPECT() *MockFileMetadataRepository_Expecter {
	return &MockFileMetadataRepository_Expecter{mock: &_m.Mock}
}

// CreateFileMetadata provides a mock function with given fields: _a0, _a1
func (_m *MockFileMetadataRepository) CreateFileMetadata(_a0 context.Context, _a1 FileMetadata) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateFileMetadata")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, FileMetadata) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileMetadataRepository_CreateFileMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFileMetadata'
type MockFileMetadataRepository_CreateFileMetadata_Call struct {
	*mock.Call
}

// CreateFileMetadata is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 FileMetadata
func (_e *MockFileMetadataRepository_Expecter) CreateFileMetadata(_a0 interface{}, _a1 interface{}) *MockFileMetadataRepository_CreateFileMetadata_Call {
	return &MockFileMetadataRepository_CreateFileMetadata_Call{Call: _e.mock.On("CreateFileMetadata", _a0, _a1)}
}

func (_c *MockFileMetadataRepository_CreateFileMetadata_Call) Run(run func(_a0 context.Context, _a1 FileMetadata)) *MockFileMetadataRepository_CreateFileMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(FileMetadata))
	})
	return _c
}

func (_c *MockFileMetadataRepository_CreateFileMetadata_Call) Return(_a0 error) *MockFileMetadataRepository_CreateFileMetadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileMetadataRepository_CreateFileMetadata_Call) RunAndReturn(run func(context.Context, FileMetadata) error) *MockFileMetadataRepository_CreateFileMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileMetadataRepository creates a new instance of MockFileMetadataRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileMetadataRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileMetadataRepository {
	mock := &MockFileMetadataRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
