// Code generated by mockery v2.38.0. DO NOT EDIT.

package file

import mock "github.com/stretchr/testify/mock"

// MockFileMetadataRepository is an autogenerated mock type for the FileMetadataRepository type
type MockFileMetadataRepository struct {
	mock.Mock
}

type MockFileMetadataRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileMetadataRepository) EXPECT() *MockFileMetadataRepository_Expecter {
	return &MockFileMetadataRepository_Expecter{mock: &_m.Mock}
}

// NewMockFileMetadataRepository creates a new instance of MockFileMetadataRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileMetadataRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileMetadataRepository {
	mock := &MockFileMetadataRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
