on:
  push:
    paths-ignore:
      - '**/**.md'
      - 'documentation/**'

env:
  MAJOR: 0
  MINOR: 7
  PATCH: 0
  GIN_MODE: release
  MAIN_PACKAGE: 'cmd/file-store-svc/main.go'

concurrency: ci-${{ github.ref }}

name: restaurant-file-store-svc-ci

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.26'
          cache: true
      - name: "Installed go version"
        run: go version

      - name: Compute semantic version
        id: semantic_version
        uses: KinNeko-De/compute-semantic-version-action@v1
        with:
          major: ${{ env.MAJOR }}
          minor: ${{ env.MINOR }}
          patch: ${{ env.PATCH }}

      - name: Prepare git tags
        id: prepare_tag
        run: |
          echo "git_tag=v${{ steps.semantic_version.outputs.semantic_version }}" >> $GITHUB_OUTPUT
          echo "git_tag_major=v${{ env.MAJOR }}" >> $GITHUB_OUTPUT
      
      - name: 'Version upgraded?'
        id: version_check
        run: |
          current_version="v${{ steps.semantic_version.outputs.next_default_branch_version }}"
          last_main_version=$(git tag --list | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          if [[ -z "$last_main_version" ]]; then
            echo "No previous version found, proceeding..."
          else
            echo "Compare last main version: $last_main_version with current version: $current_version"
            if [[ $(echo -e "$current_version\n$last_main_version" | sort -V | head -n 1) == "$current_version" ]]; then
              echo "Please upgrade the version number to a higher value than $last_main_version"
              exit 1
            fi
          fi
          
      - name: Write version txt
        id: version_txt
        run: |
          tee build/version.txt <<< ${{ steps.semantic_version.outputs.semantic_version }}
      - name: "Build"
        run: |
          go build -o bin/app ./${{ env.MAIN_PACKAGE }}
      - name: "UnitTest"
        run: |
          go test ./... -race -coverpkg=all -coverprofile=unit_coverage.out -timeout 5m --tags=unit
      - name: Create docker network
        run: 'docker network create restaurant'
      - name: Start system under test
        run: docker compose -f scripts/sut/sut-compose.yml up --wait --quiet-pull
      - name: "ComponentTest"
        run: |
          go test ./... -race -coverpkg=all -coverprofile=component_coverage.out -timeout=5m --tags=component
      - name: "AcceptanceTest"
        run: |
          go test ./... -race -coverpkg=all -coverprofile=acceptance_coverage.out -timeout=5m --tags=acceptance --parallel 1
      - name: Show system under test logs
        if: always()
        run: docker compose -f scripts/sut/sut-compose.yml logs
      - name: Stop system under test
        if: always()
        run: docker compose -f scripts/sut/sut-compose.yml down --volumes
      - name: "Exclude codecoverage and combine coverage files" # known bug that files parameter is ignored https://github.com/codecov/codecov-action/issues/1285 so unfiltered files must be overriden
        run: |
          grep -v -E -f .covignore unit_coverage.out > unit_coverage.filtered.out
          mv unit_coverage.filtered.out unit_coverage.out
          grep -v -E -f .covignore component_coverage.out > component_coverage.filtered.out
          mv component_coverage.filtered.out component_coverage.out
          grep -v -E -f .covignore acceptance_coverage.out > acceptance_coverage.filtered.out
          mv acceptance_coverage.filtered.out acceptance_coverage.out
      - name: "Code coverage" # known bug that files parameter is ignored https://github.com/codecov/codecov-action/issues/1285, upload all files
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
      - name: "Build artifacts"
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/dockerfile
          push: false
          tags: ${{ steps.semantic_version.outputs.semantic_version }} # on push later
      - name: Create semantic versioning git tag for golang
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ steps.semantic_version.outputs.semantic_version }}",
              sha: context.sha
            })
